# Generated by Django 3.2.7 on 2021-09-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.title'),
        ),
    ]
