# Generated by Django 3.2.7 on 2021-10-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_problem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.app'),
        ),
    ]
