# Generated by Django 3.2.7 on 2021-10-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20211011_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='test_solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
