# Generated by Django 3.2.7 on 2021-10-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_auto_20211020_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='confirmed',
        ),
    ]
