# Generated by Django 3.2.7 on 2022-01-24 09:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cittu_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunitreport',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
